/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlbumItem: typeof import('./src/components/AlbumItem.vue')['default']
    AlbumLeft: typeof import('./src/components/AlbumLeft.vue')['default']
    CardMD: typeof import('./src/components/CardMD.vue')['default']
    CateMenu: typeof import('./src/components/CateMenu.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    PlainCard: typeof import('./src/components/PlainCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfInfo: typeof import('./src/components/selfInfo.vue')['default']
    Word: typeof import('./src/components/word.vue')['default']
  }
}
